### ISSUE TITLE
zero width spaces between consecutive hyphens in docs

### ISSUE THREAD

**Issue by jankyupeblik** [rubygems/guides#247] opened 2019-10-15 16:50 UTC
https://guides.rubygems.org/command-reference/#gem-environment

Like this: `-​-config-file`.

Makes searching for `--` on the page impossible.

(https://help.github.com/en/articles/transferring-an-issue-to-another-repository)

**Comment by say8425** [comment] 2019-10-31 01:52
<img width="724" alt="스크린샷 2019-10-31 오전 10 16 11" src="https://user-images.githubusercontent.com/3258867/67911377-aa8ee300-fbc9-11e9-9ff4-b2d759647252.png">

I got same issue. And when I copy and paste in terminal, it looked weird 
and did not work.

So I tried to find [code](https://github.com/rubygems/guides/blame/gh-pages/command-reference.md#L678) in [command-reference.md](https://github.com/rubygems/guides/blob/gh-pages/command-reference.md) and there was `-N, -&#8203;-no-document`. And also many another codes used `&#8203`, instead of `-`. What is `&#8203;`?

<img width="1651" alt="스크린샷 2019-10-31 오전 10 37 30" src="https://user-images.githubusercontent.com/3258867/67911724-e4acb480-fbca-11e9-9b79-c06aa05b2285.png">

Finally I tried to remove `&#8203;` but it maked more complicated. -- was becoming just long —.
And I can found this code was committed in January 2012. Is this code was unfixable legacy?

**Comment by duckinator** [comment] 2020-06-25 18:12
Just confirmed this is still a problem. In theory, I think wrapping the arguments with backticks (since it's markdown, after all) and removing the zero-width spaces may fix the problem.

**Comment by deivid-rodriguez** [comment] 2021-03-08 16:34
Fixed by #272.

**Closed by deivid-rodriguez** 2021-03-08 16:34 UTC
