### ISSUE TITLE
Some characters are replaced with spaces in Gem::Specification#files document 

### ISSUE THREAD

**Issue by pocke** [rubygems/guides#249] opened 2020-01-09 12:51 UTC
https://guides.rubygems.org/specification-reference/#files

The example code is the following

```
require 'rake'
spec.files = FileList['lib     .rb',
                      'bin/*',
                      '[A-Z]*',
                      'test/   *'].to_a

# or without Rake...
spec.files = Dir['lib/   *.rb'] + Dir['bin/*']
spec.files += Dir['[A-Z]*'] + Dir['test/**/*']
spec.files.reject! { |fn| fn.include? "CVS" }
```

But it looks incorrect. `'lib     .rb'` is strange. It should be `'lib/**/*.rb'`. 
https://github.com/rubygems/rubygems/blob/778b7440d78f06bebdaef3cb67f4ab7f97635f51/lib/rubygems/specification.rb#L241-L252

**Comment by duckinator** [comment] 2020-06-25 18:19
It looks like it's just in markdown file like that: https://github.com/rubygems/guides/blob/gh-pages/specification-reference.md#files

I think this page needs to be regenerated.

**Comment by duckinator** [comment] 2020-06-25 18:27
It's auto-generated; see: https://github.com/rubygems/guides/blob/gh-pages/Rakefile#L30-L35

**Comment by duckinator** [comment] 2020-06-25 20:34
The command that's ultimately run is: `rdoc --quiet -o html -T jekdoc ../rubygems/lib/rubygems/specification.rb`

Where:
- `-o html` is saying to put the generated files in the directory `./html/`.
- `jekdoc` is referring to https://github.com/rubygems/guides/tree/gh-pages/rdoc/generator/template/jekdoc
- `../rubygems/lib/rubygems/specification.rb` is referring to https://github.com/rubygems/rubygems/blob/v3.0.0/lib/rubygems/specification.rb (I went with the RubyGems tag that `specification-reference.md` is supposed to be generated from currently.)

It generates an intermediate HTML file, which parts are extracted from. I've confirmed that the generated HTML file is _already_ missing parts of it, which means the problem is in rdoc itself.

**Comment by duckinator** [comment] 2020-06-25 20:46
Reproduced by running `rdoc test.rb`, where `test.rb` contains:

```
# x
#   'a/**/*b'
#   'c/**/*'
def foo; end
```
![Screenshot_20200625_164550](https://user-images.githubusercontent.com/39698/85793666-58c03d80-b703-11ea-84a9-3496bb267b35.png)

**Comment by duckinator** [comment] 2020-06-25 20:53
Possibly related: https://github.com/ruby/rdoc/issues/455#issuecomment-649811793

**Comment by aycabta** [comment] 2020-08-06 16:45
Would you try RDoc 6.2.0 or later?

**Comment by abitrolly** [comment] 2020-10-31 12:16
@aycabta it is impossible to try newer RDoc, because the repo uses Jekyll which is run by GitHub Pages, and the latter doesn't allow running custom gems.

I too couldn't understand the documented syntax for masks for `Dir` - it didn't work for me - and after an hour or two I ended here.

**Comment by abitrolly** [comment] 2020-10-31 12:18
The solution is to deploy pages with Travis. https://travis-ci.org/github/rubygems/guides

**Comment by deivid-rodriguez** [comment] 2021-03-14 19:30
It sounds like we're using a fixed rdoc now since I tried regenerating the guides after pushing https://github.com/rubygems/guides/commit/9276fa232f8c44913e33c1f3f0e9350a2bd61bc1 and the whitespace didn't creep in again. So I'll close this!

**Closed by deivid-rodriguez** 2021-03-14 19:30 UTC
